name: 'DeployManagerSF'
description: 'DeployManagerSF'
author: 'vectorx'
inputs:
  customer-id-deploy:
    description: 'Customer id deploy'     
    required: true
    type: string
  customer-id:
    description: 'Customer Id'
    required: true
    type: string
  release-id:
    description: 'Release Id'     
    required: true
    type: string
  git-user:
    description: 'Git user'
    required: true
    type: string
  sf-user:
    description: 'Salesforce user'
    required: true
    type: string
  sf-user-deploy:
    description: 'Salesforce user deploy'
    required: true
    type: string
  enviroment-deploy:
    description: 'Enviroment'
    required: true
    default: 'https://login.salesforce.com' 
    type: choice
    options: 
    - https://login.salesforce.com
    - https://test.salesforce.com
  enviroment:
    description: 'Enviroment'
    required: true
    default: 'https://login.salesforce.com'
    type: choice
    options: 
    - https://login.salesforce.com
    - https://test.salesforce.com
  type:
    description: 'Type'
    required: true
    type: choice
    default: 'validation'
    options: 
    - deploy
    - validation
    - validation-deploy
  auth-token:
    description: 'Type'
    required: true
    type: string
  create-release:
    description: 'create-release'
    required: true
    type: boolean
runs:
  using: 'node16'
  main: 'dist/index.js'